name: Terraform Ex3 Apply
on:   
  push:
    branches:
      - 'ex3**'
jobs:
  create-infra:
    name: Terraform Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ex3-cicd-feature-env
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'eu-west-2'

      # Config for S3 Backend
      S3_BACKEND_BUCKET: ${{ secrets.S3_BACKEND_BUCKET }}
      S3_BACKEND_KMS_KEY_ID: ${{ secrets.S3_BACKEND_KMS_KEY_ID }}
      S3_BACKEND_AWS_REGION: 'eu-west-2'
      S3_BACKEND_ENCRYPT: 'true'





    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.5

      - name: Give runner permissions for all files in folder recursively
        run: chmod -R 700 ./

      - name: Print Environment Variables - for debugging
        run: printenv


      - name: Set branch environment variable
        run: |
          . ./support_scripts/set-branch-env-var.sh
          echo "TF_VAR_branch is ${TF_VAR_branch}"

      - name: Execute generate config.s3.tfbackend
        run: |
          ./support_scripts/generate-backend-tf.sh
          cat config.s3.tfbackend

      - name: Terraform Format
        id: terraform-fmt
        run: terraform fmt -check
      
      - name: Terraform Init
        id: terraform-init -backend-config="path=config.s3.tfbackend"
        run: terraform init -input=false

      - name: Terraform Validate
        id: terraform-validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: terraform-plan
        run: terraform plan -input=false -out=tfplan -no-color
      # - name: Terraform Output
      #   run: terraform output -json > outputs.json





