name: Terraform Ex3 Apply
on:   
  push:
    branches:
      - 'ex3**'
jobs:
  create-infra:
    name: Terraform Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ex3-cicd-feature-env
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'eu-west-2'
      S3_BACKEND_BUCKET: ${{ secrets.S3_BACKEND_BUCKET }}
      S3_BACKEND_KMS_KEY_ID: ${{ secrets.S3_BACKEND_KMS_KEY_ID }}




    steps:
      - uses: actions/checkout@v2

      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v1
      
      - run: terraform  --version

      - run: chmod -R 700 ./

      - run: printenv
      - run: . ./support_scripts/set-branch-env-var.sh

      - name: Set branch environment variable
        run: |
          . ./support_scripts/set-branch-env-var.sh
          echo "TF_VAR_branch is ${TF_VAR_branch}"



      - run: ./support_scripts/generate-backend-tf.sh
      - run: cat backend.tf

      
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan
      # - name: Terraform Output
      #   run: terraform output -json > outputs.json





